In [1]:
import pandas as pd
df1=pd.read_csv(r"/Users/priyankamalavade/Desktop/BRS/data/Audible_Catlog.csv")
df2=pd.read_csv(r"/Users/priyankamalavade/Desktop/BRS/data/Audible_Catlog_Advanced_Features.csv")

In [2]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6368 entries, 0 to 6367
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Book Name          6368 non-null   object
 1   Author             6368 non-null   object
 2   Rating             6368 non-null   float64
 3   Number of Reviews  5737 non-null   float64
 4   Price              6365 non-null   float64
dtypes: float64(3), object(2)
memory usage: 248.9+ KB

In [3]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4464 entries, 0 to 4463
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Book Name          4464 non-null   object
 1   Author             4464 non-null   object
 2   Rating             4464 non-null   float64
 3   Number of Reviews  4043 non-null   float64
 4   Price              4464 non-null   int64
 5   Description        4458 non-null   object
 6   Listening Time     4464 non-null   object
 7   Ranks and Genre    4464 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 279.1+ KB

In [4]:
df1.head()

,Book Name,Author,Rating,Number of Reviews,Price
0,Think Like a Monk: The Secret of How to Harnes...,Jay Shetty,4.9,313.0,10080.0
1,Ikigai: The Japanese Secret to a Long and Happ...,Héctor García,4.6,3658.0,615.0
2,The Subtle Art of Not Giving a F*ck: A Counter...,Mark Manson,4.4,20174.0,10378.0
3,Atomic Habits: An Easy and Proven Way to Build...,James Clear,4.6,4614.0,888.0
4,Life's Amazing Secrets: How to Find Balance an...,Gaur Gopal Das,4.6,4302.0,1005.0

In [5]:
df2.head()

,Book Name,Author,Rating,Number of Reviews,Price,Description,Listening Time,Ranks and Genre
0,Think Like a Monk: The Secret of How to Harnes...,Jay Shetty,4.9,371.0,10080,"Over the past three years, Jay Shetty has beco...",10 hours and 54 minutes,",#1 in Audible Audiobooks & Originals (See Top..."
1,Ikigai: The Japanese Secret to a Long and Happ...,Héctor García,4.6,3682.0,615,Brought to you by Penguin.,3 hours and 23 minutes,",#2 in Audible Audiobooks & Originals (See Top..."
2,The Subtle Art of Not Giving a F*ck: A Counter...,Mark Manson,4.4,20306.0,10378,"In this generation-defining self-help guide, a...",5 hours and 17 minutes,",#3 in Audible Audiobooks & Originals (See Top..."
3,Atomic Habits: An Easy and Proven Way to Build...,James Clear,4.6,4678.0,888,Brought to you by Penguin.,5 hours and 35 minutes,",#5 in Audible Audiobooks & Originals (See Top..."
4,Life's Amazing Secrets: How to Find Balance an...,Gaur Gopal Das,4.6,4308.0,1005,"Stop going through life, Start growing throug...",6 hours and 25 minutes,",#6 in Audible Audiobooks & Originals (See Top..."

In [6]:
# Merge datasets on 'Book Name' and 'Author'
merged_df = pd.merge(df1, df2, on=['Book Name', 'Author'], suffixes=('_df1', '_df2'))

In [7]:
merged_df.head()

,Book Name,Author,Rating_df1,Number of Reviews_df1,Price_df1,Rating_df2,Number of Reviews_df2,Price_df2,Description,Listening Time,Ranks and Genre
0,Think Like a Monk: The Secret of How to Harnes...,Jay Shetty,4.9,313.0,10080.0,4.9,371.0,10080,"Over the past three years, Jay Shetty has beco...",10 hours and 54 minutes,",#1 in Audible Audiobooks & Originals (See Top..."
1,Ikigai: The Japanese Secret to a Long and Happ...,Héctor García,4.6,3658.0,615.0,4.6,3682.0,615,Brought to you by Penguin.,3 hours and 23 minutes,",#2 in Audible Audiobooks & Originals (See Top..."
2,The Subtle Art of Not Giving a F*ck: A Counter...,Mark Manson,4.4,20174.0,10378.0,4.4,20306.0,10378,"In this generation-defining self-help guide, a...",5 hours and 17 minutes,",#3 in Audible Audiobooks & Originals (See Top..."
3,Atomic Habits: An Easy and Proven Way to Build...,James Clear,4.6,4614.0,888.0,4.6,4678.0,888,Brought to you by Penguin.,5 hours and 35 minutes,",#5 in Audible Audiobooks & Originals (See Top..."
4,Life's Amazing Secrets: How to Find Balance an...,Gaur Gopal Das,4.6,4302.0,1005.0,4.6,4308.0,1005,"Stop going through life, Start growing throug...",6 hours and 25 minutes,",#6 in Audible Audiobooks & Originals (See Top..."

In [8]:
#  Drop duplicate columns post-merge by keeping one of the duplicates
# keep the 'Rating_df1', 'Number of Reviews_df1', and 'Price_df1' and drop the others
merged_df.drop(['Rating_df2', 'Number of Reviews_df2', 'Price_df2'], axis=1, inplace=True)

In [9]:
# Rename kept columns for clarity
merged_df.rename(columns={
    'Rating_df1': 'Rating',
    'Number of Reviews_df1': 'Number of Reviews',
    'Price_df1': 'Price'
}, inplace=True)

In [10]:
# Drop records with missing critical fields
merged_df.dropna(subset=['Rating', 'Number of Reviews', 'Price', 'Description'], inplace=True)

In [11]:
merged_df

,Book Name,Author,Rating,Number of Reviews,Price,Description,Listening Time,Ranks and Genre
0,Think Like a Monk: The Secret of How to Harnes...,Jay Shetty,4.9,313.0,10080.0,"Over the past three years, Jay Shetty has beco...",10 hours and 54 minutes,",#1 in Audible Audiobooks & Originals (See Top..."
1,Ikigai: The Japanese Secret to a Long and Happ...,Héctor García,4.6,3658.0,615.0,Brought to you by Penguin.,3 hours and 23 minutes,",#2 in Audible Audiobooks & Originals (See Top..."
2,The Subtle Art of Not Giving a F*ck: A Counter...,Mark Manson,4.4,20174.0,10378.0,"In this generation-defining self-help guide, a...",5 hours and 17 minutes,",#3 in Audible Audiobooks & Originals (See Top..."
3,Atomic Habits: An Easy and Proven Way to Build...,James Clear,4.6,4614.0,888.0,Brought to you by Penguin.,5 hours and 35 minutes,",#5 in Audible Audiobooks & Originals (See Top..."
4,Life's Amazing Secrets: How to Find Balance an...,Gaur Gopal Das,4.6,4302.0,1005.0,"Stop going through life, Start growing throug...",6 hours and 25 minutes,",#6 in Audible Audiobooks & Originals (See Top..."
...,...,...,...,...,...,...,...,...
4244,The Death of WCW,R.D. Reynolds,4.6,271.0,836.0,"Sorry, we just need to make sure you're not a ...",-1,-1
4245,The Prophet & The Wanderer,Khalil Gibran,4.1,6.0,539.0,"Sorry, we just need to make sure you're not a ...",-1,-1
4246,The Prophet & The Wanderer,Khalil Gibran,4.1,6.0,539.0,"Sorry, we just need to make sure you're not a ...",-1,-1
4247,Make Today Count: The Secret of Your Success I...,John C. Maxwell,4.7,301.0,500.0,"Sorry, we just need to make sure you're not a ...",-1,-1
4248,Make Today Count: The Secret of Your Success I...,John C. Maxwell,4.7,301.0,500.0,"Sorry, we just need to make sure you're not a ...",-1,-1

In [12]:
# Convert Listening Time to total minutes
def convert_time_to_minutes(time_str):
    try:
        parts = time_str.lower().replace('minutes', '').replace('minute', '').replace('hours', '').replace('hour', '').split('and')
        hours = int(parts[0].strip()) if len(parts) > 0 else 0
        minutes = int(parts[1].strip()) if len(parts) > 1 else 0
        return hours * 60 + minutes
    except:
        return None

In [13]:
merged_df['Listening Time (minutes)'] = merged_df['Listening Time'].apply(convert_time_to_minutes)

In [14]:
merged_df['Listening Time (minutes)']

0       654.0
1       203.0
2       317.0
3       335.0
4       385.0
        ...
4244    -60.0
4245    -60.0
4246    -60.0
4247    -60.0
4248    -60.0
Name: Listening Time (minutes), Length: 3833, dtype: float64

In [15]:
#  Drop  missing converted time values
merged_df.dropna(subset=['Listening Time (minutes)'], inplace=True)

In [16]:
# Remove duplicates
merged_df.drop_duplicates(subset=['Book Name', 'Author'], inplace=True)

In [17]:
# Final cleanup: drop unnecessary original columns
merged_df = merged_df.drop(columns=['Listening Time'])

In [18]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3025 entries, 0 to 4235
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Book Name                 3025 non-null   object
 1   Author                    3025 non-null   object
 2   Rating                    3025 non-null   float64
 3   Number of Reviews         3025 non-null   float64
 4   Price                     3025 non-null   float64
 5   Description               3025 non-null   object
 6   Ranks and Genre           3025 non-null   object
 7   Listening Time (minutes)  3025 non-null   float64
dtypes: float64(4), object(4)
memory usage: 212.7+ KB

In [19]:
# Show some sample values from the original 'Ranks and Genre' column to inspect the format
sample_ranks_genre = merged_df['Ranks and Genre'].dropna().unique()[:10]
sample_ranks_genre

array([',#1 in Audible Audiobooks & Originals (See Top 100 in Audible Audiobooks & Originals),#1 in Personal Success,#1 in Stress Management,#2 in Society & Culture (Books)',
       ',#2 in Audible Audiobooks & Originals (See Top 100 in Audible Audiobooks & Originals),#1 in Meditation (Audible Audiobooks & Originals),#1 in Self-Esteem,#2 in Personal Success',
       ',#3 in Audible Audiobooks & Originals (See Top 100 in Audible Audiobooks & Originals),#3 in Personal Success,#16 in Personal Development & Self-Help',
       ',#5 in Audible Audiobooks & Originals (See Top 100 in Audible Audiobooks & Originals),#1 in Psychology (Audible Audiobooks & Originals),#3 in Stress Management,#4 in Personal Success',
       ',#6 in Audible Audiobooks & Originals (See Top 100 in Audible Audiobooks & Originals),#1 in Literary Essays,#1 in Essays (Books),#1 in Spiritualism',
       ',#1 Free in Audible Audiobooks & Originals (See Top 100 in Audible Audiobooks & Originals),#1 in Leadership,#1 in Business Careers',
       ',#4 in Audible Audiobooks & Originals (See Top 100 in Audible Audiobooks & Originals),#1 in Anthropology (Audible Audiobooks & Originals),#1 in History of Civilization,#2 in Anthropology (Books)',
       ',#7 in Audible Audiobooks & Originals (See Top 100 in Audible Audiobooks & Originals),#1 in Personal Finance,#1 in Investing & Trading,#4 in Analysis & Strategy',
       ',#9 in Audible Audiobooks & Originals (See Top 100 in Audible Audiobooks & Originals),#2 in Personal Finance,#2 in Investing & Trading,#39 in Personal Development & Self-Help',
       ',#8 in Audible Audiobooks & Originals (See Top 100 in Audible Audiobooks & Originals),#1 in Sleep Disorders,#6 in Personal Success,#8 in Healthy Living & Wellness'],
      dtype=object)

In [20]:
import re

# Function to extract exact genres excluding general categories
def extract_exact_genre(rank_str):
    try:
        genres = re.findall(r'#\d+\s+in\s+([^(,]+)', rank_str)
        # Filter out generic or platform-specific categories
        filtered = [g.strip() for g in genres if "Audible Audiobooks & Originals" not in g]
        return filtered[0] if filtered else None
    except:
        return None

# Apply extraction to each row
merged_df['Genre'] = merged_df['Ranks and Genre'].apply(extract_exact_genre)

# Check value counts for genres extracted
genre_counts = merged_df['Genre'].value_counts()
merged_df[['Book Name', 'Genre']].head(), genre_counts

(                                           Book Name             Genre
 0  Think Like a Monk: The Secret of How to Harnes...  Personal Success
 1  Ikigai: The Japanese Secret to a Long and Happ...        Meditation
 2  The Subtle Art of Not Giving a F*ck: A Counter...  Personal Success
 3  Atomic Habits: An Easy and Proven Way to Build...        Psychology
 4  Life's Amazing Secrets: How to Find Balance an...   Literary Essays,
 Genre
 Personal Success                           60
 Classic Literature                         20
 Contemporary Romance                       19
 Leadership                                 18
 Meditation                                 17
                                            ..
 Christian Classic & Allegorical Fiction     1
 Language Learning                           1
 Philosopher Biographies                     1
 Theology                                    1
 Stories in Verse for Children               1
 Name: count, Length: 596, dtype: int64)

In [21]:
import re

def extract_best_rank(rank_str):
    ranks = re.findall(r'#(\d+)\s+in\s+([^(,]+)', rank_str)
    if not ranks:
        return None
    # Find the minimum rank value and corresponding genre
    best = min(ranks, key=lambda x: int(x[0]))
    return int(best[0])  # Return rank number

merged_df['Rank'] = merged_df['Ranks and Genre'].apply(extract_best_rank)

In [22]:
merged_df

,Book Name,Author,Rating,Number of Reviews,Price,Description,Ranks and Genre,Listening Time (minutes),Genre,Rank
0,Think Like a Monk: The Secret of How to Harnes...,Jay Shetty,4.9,313.0,10080.0,"Over the past three years, Jay Shetty has beco...",",#1 in Audible Audiobooks & Originals (See Top...",654.0,Personal Success,1.0
1,Ikigai: The Japanese Secret to a Long and Happ...,Héctor García,4.6,3658.0,615.0,Brought to you by Penguin.,",#2 in Audible Audiobooks & Originals (See Top...",203.0,Meditation,1.0
2,The Subtle Art of Not Giving a F*ck: A Counter...,Mark Manson,4.4,20174.0,10378.0,"In this generation-defining self-help guide, a...",",#3 in Audible Audiobooks & Originals (See Top...",317.0,Personal Success,3.0
3,Atomic Habits: An Easy and Proven Way to Build...,James Clear,4.6,4614.0,888.0,Brought to you by Penguin.,",#5 in Audible Audiobooks & Originals (See Top...",335.0,Psychology,1.0
4,Life's Amazing Secrets: How to Find Balance an...,Gaur Gopal Das,4.6,4302.0,1005.0,"Stop going through life, Start growing throug...",",#6 in Audible Audiobooks & Originals (See Top...",385.0,Literary Essays,1.0
...,...,...,...,...,...,...,...,...,...,...
4224,The Death of WCW,R.D. Reynolds,4.6,271.0,836.0,"Sorry, we just need to make sure you're not a ...",-1,-60.0,None,NaN
4226,The Prophet & The Wanderer,Khalil Gibran,4.1,6.0,539.0,"Sorry, we just need to make sure you're not a ...",-1,-60.0,None,NaN
4228,Make Today Count: The Secret of Your Success I...,John C. Maxwell,4.7,301.0,500.0,"Sorry, we just need to make sure you're not a ...",-1,-60.0,None,NaN
4234,"Kill the Company: End the Status Quo, Start an...",Lisa Bodell,4.2,26.0,586.0,\n\nOops!\nIt's rush hour and traffic is pilin...,-1,-60.0,None,NaN
4235,Dr. Bernstein's Diabetes Solution: The Complet...,Richard K. Bernstein,4.6,1088.0,500.0,"Originally published in 1997, Dr. Bernstein's ...",",#1,655 in Audible Audiobooks & Originals (See...",1053.0,Low Carb Diets,1.0

In [23]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3025 entries, 0 to 4235
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Book Name                 3025 non-null   object
 1   Author                    3025 non-null   object
 2   Rating                    3025 non-null   float64
 3   Number of Reviews         3025 non-null   float64
 4   Price                     3025 non-null   float64
 5   Description               3025 non-null   object
 6   Ranks and Genre           3025 non-null   object
 7   Listening Time (minutes)  3025 non-null   float64
 8   Genre                     1587 non-null   object
 9   Rank                      1587 non-null   float64
dtypes: float64(5), object(5)
memory usage: 260.0+ KB

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

# Step 1: Create a subset with known genres and descriptions
known_genres = merged_df[merged_df['Genre'].notnull()]
unknown_genres = merged_df[merged_df['Genre'].isnull()]

# Step 2: Vectorize descriptions using TF-IDF
vectorizer = TfidfVectorizer(stop_words='english', max_features=5000)
tfidf_known = vectorizer.fit_transform(known_genres['Description'])
tfidf_unknown = vectorizer.transform(unknown_genres['Description'])

# Step 3: Use Nearest Neighbors to find closest match by description
nn = NearestNeighbors(n_neighbors=1, metric='cosine')
nn.fit(tfidf_known)

# Step 4: Predict genres for missing entries
distances, indices = nn.kneighbors(tfidf_unknown)
predicted_genres = known_genres.iloc[indices.flatten()]['Genre'].values

# Step 5: Fill in the predicted genres
merged_df.loc[merged_df['Genre'].isnull(), 'Genre'] = predicted_genres

# Check genre fill stats
filled_genre_counts = merged_df['Genre'].value_counts().head(10)
merged_df[['Book Name', 'Genre']].head(), filled_genre_counts

(                                           Book Name             Genre
 0  Think Like a Monk: The Secret of How to Harnes...  Personal Success
 1  Ikigai: The Japanese Secret to a Long and Happ...        Meditation
 2  The Subtle Art of Not Giving a F*ck: A Counter...  Personal Success
 3  Atomic Habits: An Easy and Proven Way to Build...        Psychology
 4  Life's Amazing Secrets: How to Find Balance an...   Literary Essays,
 Genre
 Religion & Philosophy    669
 Fantasy                  399
 Personal Success          75
 Contemporary Romance      28
 Literary Fiction          26
 Indian Literature         23
 Meditation                22
 Classic Literature        22
 Leadership                20
 Contemporary Fiction      20
 Name: count, dtype: int64)

In [25]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3025 entries, 0 to 4235
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Book Name                 3025 non-null   object
 1   Author                    3025 non-null   object
 2   Rating                    3025 non-null   float64
 3   Number of Reviews         3025 non-null   float64
 4   Price                     3025 non-null   float64
 5   Description               3025 non-null   object
 6   Ranks and Genre           3025 non-null   object
 7   Listening Time (minutes)  3025 non-null   float64
 8   Genre                     3025 non-null   object
 9   Rank                      1587 non-null   float64
dtypes: float64(5), object(5)
memory usage: 260.0+ KB

In [26]:
# Option 2: Fill missing Rank values with a default high number (e.g., 999) to indicate unranked books
merged_df['Rank'] = merged_df['Rank'].fillna(999)

# Confirm the update
merged_df['Rank'].isnull().sum(), merged_df['Rank'].value_counts().head()

(np.int64(0),
 Rank
 999.0    1438
 1.0       264
 2.0       143
 3.0       128
 4.0        85
 Name: count, dtype: int64)

In [27]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3025 entries, 0 to 4235
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Book Name                 3025 non-null   object
 1   Author                    3025 non-null   object
 2   Rating                    3025 non-null   float64
 3   Number of Reviews         3025 non-null   float64
 4   Price                     3025 non-null   float64
 5   Description               3025 non-null   object
 6   Ranks and Genre           3025 non-null   object
 7   Listening Time (minutes)  3025 non-null   float64
 8   Genre                     3025 non-null   object
 9   Rank                      3025 non-null   float64
dtypes: float64(5), object(5)
memory usage: 260.0+ KB

In [28]:
merged_df.head()

,Book Name,Author,Rating,Number of Reviews,Price,Description,Ranks and Genre,Listening Time (minutes),Genre,Rank
0,Think Like a Monk: The Secret of How to Harnes...,Jay Shetty,4.9,313.0,10080.0,"Over the past three years, Jay Shetty has beco...",",#1 in Audible Audiobooks & Originals (See Top...",654.0,Personal Success,1.0
1,Ikigai: The Japanese Secret to a Long and Happ...,Héctor García,4.6,3658.0,615.0,Brought to you by Penguin.,",#2 in Audible Audiobooks & Originals (See Top...",203.0,Meditation,1.0
2,The Subtle Art of Not Giving a F*ck: A Counter...,Mark Manson,4.4,20174.0,10378.0,"In this generation-defining self-help guide, a...",",#3 in Audible Audiobooks & Originals (See Top...",317.0,Personal Success,3.0
3,Atomic Habits: An Easy and Proven Way to Build...,James Clear,4.6,4614.0,888.0,Brought to you by Penguin.,",#5 in Audible Audiobooks & Originals (See Top...",335.0,Psychology,1.0
4,Life's Amazing Secrets: How to Find Balance an...,Gaur Gopal Das,4.6,4302.0,1005.0,"Stop going through life, Start growing throug...",",#6 in Audible Audiobooks & Originals (See Top...",385.0,Literary Essays,1.0

In [29]:
# Convert 'Number of Reviews' and 'Rank' to integer type
merged_df['Number of Reviews'] = merged_df['Number of Reviews'].astype(int)
merged_df['Rank'] = merged_df['Rank'].astype(int)

In [30]:
# Convert 'Genre' and 'Ranks and Genre' to category dtype
merged_df['Genre'] = merged_df['Genre'].astype('category')
merged_df['Ranks and Genre'] = merged_df['Ranks and Genre'].astype('category')

In [31]:
# Check for any missing data
print(merged_df.isnull().sum())

Book Name                   0
Author                      0
Rating                      0
Number of Reviews           0
Price                       0
Description                 0
Ranks and Genre             0
Listening Time (minutes)    0
Genre                       0
Rank                        0
dtype: int64

In [ ]:
merged_df = merged_df.drop(columns=['Ranks and Genre'])

In [33]:
merged_df.head(2)

,Book Name,Author,Rating,Number of Reviews,Price,Description,Listening Time (minutes),Genre,Rank
0,Think Like a Monk: The Secret of How to Harnes...,Jay Shetty,4.9,313,10080.0,"Over the past three years, Jay Shetty has beco...",654.0,Personal Success,1
1,Ikigai: The Japanese Secret to a Long and Happ...,Héctor García,4.6,3658,615.0,Brought to you by Penguin.,203.0,Meditation,1

In [34]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3025 entries, 0 to 4235
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Book Name                 3025 non-null   object
 1   Author                    3025 non-null   object
 2   Rating                    3025 non-null   float64
 3   Number of Reviews         3025 non-null   int64
 4   Price                     3025 non-null   float64
 5   Description               3025 non-null   object
 6   Listening Time (minutes)  3025 non-null   float64
 7   Genre                     3025 non-null   category
 8   Rank                      3025 non-null   int64
dtypes: category(1), float64(3), int64(2), object(3)
memory usage: 239.4+ KB

In [37]:
merged_df.to_csv(r"/Users/priyankamalavade/Desktop/BRS/data/cleaned_dataset.csv",index=False)